### ISSUE TITLE
Error when registering

### ISSUE THREAD

**Issue by kenth-israel-goteam** [jrmldesign-official/pokemon_community#4]
![image](https://github.com/jrmldesign-official/pokemon_community/assets/125624981/3d9dbe7d-567f-490a-9869-1306cd19cfe7)

**Comment by jrmldesign-official** [comment]
Good day!

Sorry for the late response. 

I've recreated the error that you've encountered. 
![image](https://github.com/jrmldesign-official/pokemon_community/assets/70363293/81a9a638-dd8e-4c66-ac32-f4244d074a18)

To fix this look for **.env** file copy the value of **APP_KEY** except "**base64:**" 

Example:
APP_KEY=base64:**hmDTas2rEFqKz+QxEF0cKERFrHnUYiS5crzc7Ry+XP4=**

copy only the: **hmDTas2rEFqKz+QxEF0cKERFrHnUYiS5crzc7Ry+XP4=**
and paste that inside the **crypto.js** (See image below for reference)

![image](https://github.com/jrmldesign-official/pokemon_community/assets/70363293/392e8189-34df-4312-a339-01845c6c1508)
